### PR TITLE
Update LAB_AK_05_Lab1_Ex1_ATP_policies.md

### PR DESCRIPTION
**Pull request by renaudwangler**
# Module: 5
## Lab: 5

Changes proposed in this pull request:

#### Update Task1
- Need to click on "+ Block" to add a new blocked url.
- There is no (more) "all company" group in test accounts ==> Switch to select the entire domain.

### CODE REVIEW

**Comment by awillslo** [comment]
@renaudwangler  I see too there is no more All Company group.  So what I did was, before they start ATP lab, is to create an Organizational Teams named All Company, and then it becomes available for the ATP lab.  Not sure why the Lab Hoster is not setting up the template tenancy correctly.

**Comment by hrasheed-msft** [comment]
@renaudwangler Thanks for your contribution!

@awillslo If the changes you mentioned have already been merged into the lab instructions to address the "All Company" issue, should this PR be closed?

**Comment by awillslo** [comment]
@hrasheed-msft  I have not updated the lab instructions yet, but will do so.  Look for another PR

**Review by awillslo — COMMENTED** [review]
added to PR #179

**Comment by hrasheed-msft** [comment]
@renaudwangler  we have incorporated your changes into another PR. Thanks for your contribution!

**Pull request closed without merging**
